### ISSUE TITLE
It's pretty empty here ❤️ 

### ISSUE THREAD

**Issue by FabienLamonarca** [Max3uc3Planz/comics-project#1]

**Comment by max3uc3** [comment]
mdr, yeah, because we are thinking bout our project before creating it. We're on the good path I think :o

**Comment by FabienLamonarca** [comment]
Way better like that 🚀

**Comment by max3uc3** [comment]
It's just the first run, I've just initialized the stack ahaha. I've a lot of job todo now ^^
